### ISSUE TITLE
advanced examples suggestion

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#40]
hi

first thanks for mentioning me in credits but that was not necessary

second can you please add some example on how to use third party libs

i tried to use https://github.com/thephpleague/omnipay
i installed via composer, modified composer_autoload to true and i tried to use the code sample from the git page and got a Fatal error: Class 'Omnipay' not found
am i missing something ?

another package i tried to use is https://code.google.com/p/php5-image/
this one without composer
i copied the content of the src folder from the download archive to common\third_party
so i have common\third_party\Image\Image.php
i tried to add the lib to autoload_classes config and just lost myself trying to fix require_once includes

if you have the time and patience i think a demo/tutorial would be appreciated by many people

thanks again for your work and close this request if it has no value

**Comment by quasiperfect** [comment]
update

i created a library omnipay using multiplayer as example and now i get Fatal error: Cannot access property Omnipay::$factory

**Comment by ivantcholakov** [comment]
I will test installing the mentioned components and will report here.

**Comment by ivantcholakov** [comment]
@quasiperfect

About https://code.google.com/p/php5-image/

A way that I found:

Uncompress the zip, grab the folder Image/ (that is under src/) and put it inside platform/common/classes/

So, you have the folder platform/common/classes/Image/

Search the source within this folder and comment everywhere all the require_once statements.

Then within Welcome_controller, at the beginning of index() method put this testing code:

```php
$image = new Image_Image(DEFAULTFCPATH . 'assets/img/playground.jpg');

$image->attach(new Image_Fx_Resize(200));
$image->attach(new Image_Fx_Crop(0, 86));
$image->attach(new Image_Draw_Border(2, "000000"));
$image->attach(new Image_Fx_Canvassize(0, 10, 10, 0));
$watermark = new Image_Draw_Watermark(new Image_Image(DEFAULTFCPATH . 'assets/img/lib/smileys/smile.gif'));
$watermark->setPosition("br");
$image->attach($watermark);
$image->imagePng();
exit;
``` 

As a result, instead of the home page you will see a manipulated image.

**Comment by ivantcholakov** [comment]
The second way:

Grab the folder Image/ and put it within platform/common/classes/Image/third_party/pear/

You would have platform/common/classes/Image/third_party/pear/Image/

In this case you would not need to modify the sources. This library likely follows the PEAR convention.

Then run the testing code again.

**Comment by ivantcholakov** [comment]
@quasiperfect

About the Composer package I see that you have success.

This is an old forum discussion with me https://ellislab.com/forums/viewthread/246558/ It is about pure CodeIgniter, but I think, you can figure out where the mentioned files and directories are placed in this platform.

And another similar article: http://avenir.ro/codeigniter-tutorials/codeigniter-with-composer/
But there the mentioned line
require_once APPPATH.'vendor/autoload.php';
within config.php is not needed in this platform.

**Comment by ivantcholakov** [comment]
@quasiperfect 

https://github.com/npetrovski/php5-image  I am not sure whether the author is the same. I can see that refactoring for PHP 5.4 is going on there.

**Comment by quasiperfect** [comment]
hi
thanks a lot for the info

the composer part was ok to digest and i managed to understand it

about the php5-image can you explain how are the classes loaded in the first method (comment require) and second one (pear) ?

**Comment by ivantcholakov** [comment]
This is the autoloader that I maintain in this platform: https://github.com/ivantcholakov/starter-public-edition-4/blob/master/platform/bootstrap/autoload.php

It is called as early as it is possible, even before the normal configuration files are read. It is for non-Composer stuff.

(By the way, if you activate Composer too, its autoloader registers at the first place and is called at first place.)

------------------

php5-image, the first way, under classes/ subdirectory:

The autoloader looks at classes/ directory and seeks based on the class name a file, or subdirectory (or subdirectories) and file. Underscores in the class name are treated as directory separators.

The require_once lines are wrong, because the paths are relative and the base directory of the application is different. And, they are not needed, because the autoloader does the job.

classes/ is my place where I can just drop a class (without namespaces, and that is not a CodeIgniter library) and it can be used immediately everywhere.

Something similar I've proposed for those that start from clean CodeIgniter http://forum.codeigniter.com/thread-420-post-1937.html#pid1937

------------------

php5-image, the second way, under the third_party/pear/ subdirectory:

The autoloader works in the same way. But the PEAR packages do not require/need an autoloader, this is why these require_once lines inside the class files are put by the author. Again, the base directory of the application is wrong and require_once lines don't find their targets immediately.

See however this line: https://github.com/ivantcholakov/starter-public-edition-4/blob/master/platform/bootstrap/bootstrap.php#L269 The third_party/pear/ directory is at the first place in the additional include paths to be searched. Then the require_once statements work, they are not to be removed. This is how an old PEAR package can be integrated within your application only.

In the second way, the autoloader will find the Image_Image class, but the other classes within the package will be loaded by the require_once statements, as the author determined.

------------------

For this particular package php5-image - I would prefer to place it under pear/ , simply because I would not need to touch the sources.

**Comment by quasiperfect** [comment]
that was very nice and clear info
maybe you should add that to the main page i'm sure will help somebody

thanks again for all your work
