### ISSUE TITLE
replace / add validation lib

### ISSUE THREAD

**Issue by quasiperfect** [ivantcholakov/starter-public-edition-4#62]
@ivantcholakov take a look at this for a CI validation replacement lib https://github.com/vlucas/valitron

**Comment by ivantcholakov** [comment]
@quasiperfect

Do you have intention to use this component for real projects?

I can add this component, this is easy. I can not see it as a replacement of CodeIgniter's validation library however, because:

* If I need to modify/correct some rules - I don't see how to do it.
* The supported languages are not so many as of the CodeIgniter's library.

This component can be used directly, unfortunately dependency would be hard-coded. A palliative way is this component to be used for implementation of CodeIgniter's validation callback methods - at least the callback methods could be easily reworked if it is needed.

I am neutral here, it depends on your opinion - to add this component or not?

**Comment by quasiperfect** [comment]
i liked the multi-dimensional arrays validation and that is one file (i hate big components with lots of files)

i didn't propose to add this to your project (optional) i was asking more for your opinion about the lib

if it's not usefull for you don't add it i will play with the lib in some project (1month or so) and give you some feedback

thanks for your time

**Comment by ivantcholakov** [comment]
Ok
